spring.application.name=demo

# configuration for database
spring.datasource.url=jdbc:mysql://localhost:3306/todolist?useSSL=false&serverTimezone=Pacific/Auckland&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=lele8313426
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# configuration for MyBatis log output
mybatis.mapper-locations=classpath:com/todolist/demo/mappers/*.xml
mybatis.type-aliases-package=com.todolist.demo.pojo
mybatis.configuration.map-underscore-to-camel-case=true

server.port=8080